name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # - run: nix flake check
      - run: nix build ".#x86_64-unknown-linux-musl"
      - run: nix build ".#x86_64-unknown-linux-gnu"
