name: "Test"
on:
  pull_request:
  push:

jobs:
  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: nixpkgs-cross-overlay
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build ".#x86_64-unknown-linux-musl"
      - run: nix build ".#x86_64-unknown-linux-musl-static"
      # TODO fix compilation on Gnu targets
      # - run: nix build ".#x86_64-unknown-linux-gnu"
