name: "Test"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --command dprint check --verbose

  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target:
          - x86_64-unknown-linux-musl
        useLLVM: [false, true]
        isStatic: [false, true]
    runs-on: ${{ matrix.os }}
    env:
      crossSystem: '{ config = "${{ matrix.target }}"; isStatic = "${{ matrix.isStatic }}"; useLLVM = "${{ matrix.useLLVM }}"; }'
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Build packages
      - run: nix-build shell.nix --no-out-link --arg crossSystem $crossSystem
      # Test cargoDeps
      - run: nix-shell --arg crossSystem $crossSystem "./tests/crates/build_all.sh"
