name: "Test"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable    
      - run: nix develop ".#native" --command dprint check --verbose

  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: 
          - native
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-musl-static
          # Disabled due to an error: thread 'main' panicked at 'unable to generate rocksdb bindings:
          # - aarch64-unknown-linux-musl
        exclude:
          # For unknown reason Rocksdb compilation fails with an error: 
          # /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: nixpkgs-cross-overlay
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Build packages
      - run: nix build ".#${{ matrix.target }}"
      # Test cargoDeps
      - run: nix develop ".#${{ matrix.target }}" --command ./tests/crates/build_all.sh   
