name: "Test"
on:
  pull_request:

jobs:
  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target: 
          - native
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-musl-static
          - aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: nixpkgs-cross-overlay
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Build packages
      - run: nix build ".#${{ matrix.target }}"
      # Test cargoDeps
      - run: nix develop ".#${{ matrix.target }}" --command ./tests/crates/build_all.sh   
