name: "Test"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --command dprint check --verbose

  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        crossSystem:
          - 'null'
          # Musl libc
          - '{ config = "x86_64-unknown-linux-musl"; isStatic = false; useLLVM = false; }'
          - '{ config = "x86_64-unknown-linux-musl"; isStatic = true; useLLVM = false; }'
          - '{ config = "x86_64-unknown-linux-musl"; isStatic = false; useLLVM = true; }'
          - '{ config = "x86_64-unknown-linux-musl"; isStatic = true; useLLVM = true; }'
          # glibc
          - '{ config = "x86_64-unknown-linux-gnu"; isStatic = false; useLLVM = false; }'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Build packages
      - run: nix-build shell.nix --no-out-link --arg crossSystem '${{ matrix.crossSystem }}'
      # Test cargoDeps
      - run: nix-shell --pure --arg crossSystem '${{ matrix.crossSystem }}' --run ./tests/crates/build_all.sh
