name: "Test"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v14
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix flake check

  build-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        target:
          # # Musl targets
          - "target=x86_64-unknown-linux-musl"
          # - "target=x86_64-unknown-linux-musl&useLLVM=true"
          # - "target=x86_64-unknown-linux-musl&useLLVM=true&isStatic=true"
          # - "target=aarch64-unknown-linux-musl&useLLVM=true"
          # - "target=aarch64-unknown-linux-musl&useLLVM=true&isStatic=true"
          # # Gnu targets
          # - "target=aarch64-unknown-linux-gnu"
          # - "target=riscv64-unknown-linux-gnu"
          # # Broken targets
          # # - "target=x86_64-unknown-linux-gnu"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: "Build Packages"
        run:  nix build ".#pkgs?${{ matrix.target }}"
  
      - name: "Check devshell"
        run:  nix develop ".#crossShell?${{ matrix.target }}" --command "cargo-tests.sh"
  
  test-example-shell:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-cross-overlay
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: "Check devshell"
        run:  nix develop --command "cargo-tests.sh"

      - name: "Test example shell"
        run: |
          nix-shell ./examples/shell-rust-cross.nix \
            --arg crossSystem 'null' \
            --run "cargo test --manifest-path tests/crates/Cargo.toml"